### ISSUE TITLE
Recover from Organizations TooManyRequestsException

### ISSUE THREAD

**Issue by iainelder** [iainelder/orgtreepubsub#5]
If you get an error like this, you need to run dump_org again and cross your fingers:

```
Traceback (most recent call last):
  File "/home/isme/Repos/Personal/github/orgtreepubsub/orgtreepubsub.py", line 56, in raise_if_result_is_error_else_continue
    future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/isme/Repos/Personal/github/orgtreepubsub/orgtreepubsub.py", line 108, in _work
    for tag in list_tags_for_resource(client, resource):
  File "/home/isme/Repos/Personal/github/orgtreepubsub/orgtreepubsub.py", line 154, in list_tags_for_resource
    for page in pages:
  File "/home/isme/.cache/pypoetry/virtualenvs/orgtreepubsub-LeMhcv2r-py3.8/lib/python3.8/site-packages/botocore/paginate.py", line 264, in __iter__
    response = self._make_request(current_kwargs)
  File "/home/isme/.cache/pypoetry/virtualenvs/orgtreepubsub-LeMhcv2r-py3.8/lib/python3.8/site-packages/botocore/paginate.py", line 352, in _make_request
    return self._method(**current_kwargs)
  File "/home/isme/.cache/pypoetry/virtualenvs/orgtreepubsub-LeMhcv2r-py3.8/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/isme/.cache/pypoetry/virtualenvs/orgtreepubsub-LeMhcv2r-py3.8/lib/python3.8/site-packages/botocore/client.py", line 911, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.TooManyRequestsException: An error occurred (TooManyRequestsException) when calling the ListTagsForResource operation (reached max retries: 4): AWS Organizations can't complete your request because another request is already in progress. Try again later.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dump_org.py", line 12, in <module>
    main()
  File "dump_org.py", line 7, in main
    org = get_org_graph(Session())
  File "/home/isme/Repos/Personal/github/orgtreepubsub/org_graph.py", line 86, in get_org_graph
    crawl_organization(session)
  File "/home/isme/Repos/Personal/github/orgtreepubsub/orgtreepubsub.py", line 49, in crawl_organization
    raise_if_result_is_error_else_continue(future)
  File "/home/isme/Repos/Personal/github/orgtreepubsub/orgtreepubsub.py", line 61, in raise_if_result_is_error_else_continue
    raise OrganizationError() from error
type_defs.OrganizationError
```

Make it so that dump_org recovers from this error or even avoids it so that the org is dumped first time.

**Comment by iainelder** [comment]
Work around this by changing the default `max_workers` from 4 to 2.

**Comment by iainelder** [comment]
I deleted dump_org.
