### ISSUE TITLE
Allow orgtreepubsub to be imported as a module

### ISSUE THREAD

**Issue by iainelder** [iainelder/orgtreepubsub#8]
This minimal Poetry project just depends on orgtreepubsub. When I try to import the module, it fails with a ModuleNotFoundError.

```toml
[tool.poetry]
name = "proj"
version = "0.1.0"
description = ""
authors = ["Iain Samuel McLean Elder <iain@isme.es>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
orgtreepubsub = {git = "https://github.com/iainelder/orgtreepubsub"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

```console
$ poetry run python -c 'import orgtreepubsub'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/isme/.cache/pypoetry/virtualenvs/proj-Kcy8vOlE-py3.12/lib/python3.12/site-packages/orgtreepubsub.py", line 9, in <module>
    from type_defs import Account, Org, OrgUnit, Root, Tag, Parent, Resource
ModuleNotFoundError: No module named 'type_defs'
```

**Comment by iainelder** [comment]
Read about the [import system](https://docs.python.org/3/reference/import.html), modules, and packages.

**Comment by iainelder** [comment]
To fix it:

* I moved the module files into a package directory
* I added an `__init__.py`
* I used relative imports `.type_defs`, `.orgtreepubsub`
